### PR TITLE
Add data directory for skeleton files and fix dockerfile

### PR DESCRIPTION
**Pull request by dpakach**
Add data directory for skeleton files and fix dockerfile

fixes https://github.com/owncloud/owncloud-test-middleware/issues/40

### CODE REVIEW

**Review by kiranparajuli589 — COMMENTED** [review]
looks good

**Review by individual-it — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
I guess we add `apiSkeleton` and `webUISkeleton` for now because they still exist in the testing app. One day we can delete them from everywhere when we are confident that they are no longer used.

**Comment by individual-it** [comment]
Thinking of that, why do we need the skeleton here? The middleware will not be used everywhere e.g. API tests, but the skeleton is needed everywhere

**Comment by phil-davis** [comment]
> Thinking of that, why do we need the skeleton here? The middleware will not be used everywhere e.g. API tests, but the skeleton is needed everywhere

I don't understand the question/thought.

The middleware needs to be able to create a user, including with skeleton files (if requested). And the back-end server might be OCIS. And in that case, the middleware has to "simulate" the skeleton by creating the user and then creating the whole skeleton structure for the user. So the middleware has to know what are the files/folders in each skeleton.

**Pull request merged**
